# Generated by Django 3.2.4 on 2021-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='tryy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tryy',
            field=models.TextField(null=True),
        ),
    ]
