# Generated by Django 3.2.4 on 2021-07-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210702_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='tryy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tryy',
        ),
    ]
